Set required Gtk version
Fixes exceptions at start like the following:

    Traceback (most recent call last):
      File "./Py3DG200.py", line 674, in <module>
        main()
      File "./Py3DG200.py", line 237, in __init__
        self.builder.add_from_file("Gui.ui")
    gi.repository.GLib.Error: gtk-builder-error-quark: Gui.ui:11:1 Invalid object type 'GtkVBox' (6)